load("@rules_python//python:py_test.bzl", "py_test")

py_test(
    name = "execution_test",
    size = "small",
    srcs = ["execution_test.py"],
    data = ["//configs:defaults"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "compiler_costs_test",
    size = "small",
    srcs = ["compiler_costs_test.py"],
    data = ["//configs:defaults"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "pipeline_test",
    size = "small",
    srcs = ["pipeline_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "pipeline_import_test",
    size = "small",
    srcs = ["pipeline_import_test.py"],
    deps = [
        "//python:analysis_tools",
        "@com_google_protobuf//:protobuf_python",
    ],
)

py_test(
    name = "profile_report_test",
    size = "small",
    srcs = ["profile_report_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "bundle_timing_test",
    size = "small",
    srcs = ["bundle_timing_test.py"],
    data = ["//tests/fixtures/bundles:fixtures"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "llo_control_flow_test",
    size = "small",
    srcs = ["llo_control_flow_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "llo_program_test",
    size = "small",
    srcs = ["llo_program_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "launcher_test",
    size = "small",
    srcs = ["launcher_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "profile_metadata_test",
    size = "small",
    srcs = ["profile_metadata_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "sparsecore_test",
    size = "small",
    srcs = ["sparsecore_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "collection_test",
    size = "small",
    srcs = ["collection_test.py"],
    deps = ["//python:analysis_tools"],
)

py_test(
    name = "profile_import_test",
    size = "small",
    srcs = ["profile_import_test.py"],
    deps = ["//python:analysis_tools"],
)


test_suite(
    name = "python_tests",
    tests = [
        ":execution_test",
        ":compiler_costs_test",
        ":pipeline_test",
        ":pipeline_import_test",
        ":bundle_timing_test",
        ":llo_control_flow_test",
        ":llo_program_test",
        ":collection_test",
        ":launcher_test",
        ":profile_import_test",
        ":profile_metadata_test",
        ":profile_report_test",
        ":sparsecore_test",
    ],
)
